
CREATE TABLE t_item (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_id INT NOT NULL,
   store_id INT NOT NULL,
   price DOUBLE PRECISION NOT NULL,
   item_condition VARCHAR(255) NOT NULL,
   prod_date date NOT NULL,
   exp_date date NOT NULL,
   CONSTRAINT pk_t_item PRIMARY KEY (id)
);

ALTER TABLE t_item ADD CONSTRAINT FK_T_ITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES t_product (id);

ALTER TABLE t_item ADD CONSTRAINT FK_T_ITEM_ON_STORE FOREIGN KEY (store_id) REFERENCES t_store (id);

CREATE TABLE t_sale (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   store_bank_account_id INTEGER NOT NULL,
   worker_id INTEGER NOT NULL,
   sum DOUBLE PRECISION NOT NULL,
   CONSTRAINT pk_t_sale PRIMARY KEY (id)
);

ALTER TABLE t_sale ADD CONSTRAINT FK_T_SALE_ON_STORE_BANK_ACCOUNT FOREIGN KEY (store_bank_account_id) REFERENCES t_account (id);

ALTER TABLE t_sale ADD CONSTRAINT FK_T_SALE_ON_WORKER FOREIGN KEY (worker_id) REFERENCES t_worker (id);


CREATE TABLE sale_items (
  sale_id INT NOT NULL,
  items_id INT NOT NULL
);

ALTER TABLE sale_items ADD CONSTRAINT fk_sale_items_on_sale FOREIGN KEY (sale_id) REFERENCES t_sale (id);
ALTER TABLE sale_items ADD CONSTRAINT fk_sale_items_on_items FOREIGN KEY (items_id) REFERENCES t_item (id);


