CREATE TABLE t_cash_transaction (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   receiving_bank_account_id INT NOT NULL,
   sum DOUBLE PRECISION NOT NULL,
   CONSTRAINT pk_t_cashtransaction PRIMARY KEY (id)
);

ALTER TABLE t_cash_transaction ADD CONSTRAINT FK_T_CASHTRANSACTION_ON_RECEIVING_BANK_ACCOUNT FOREIGN KEY (receiving_bank_account_id) REFERENCES t_account (id);

CREATE TABLE t_cash_contract (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   provider_id INT NOT NULL,
   store_id INT NOT NULL,
   product_id INT NOT NULL,
   amount INT NOT NULL,
   signed_date date NOT NULL,
   cash_transaction_id INT NOT NULL,
   CONSTRAINT pk_t_cashcontract PRIMARY KEY (id)
);

ALTER TABLE t_cash_contract ADD CONSTRAINT FK_T_CASHCONTRACT_ON_CASH_TRANSACTION FOREIGN KEY (cash_transaction_id) REFERENCES t_cash_transaction (id);

ALTER TABLE t_cash_contract ADD CONSTRAINT FK_T_CASHCONTRACT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES t_product (id);

ALTER TABLE t_cash_contract ADD CONSTRAINT FK_T_CASHCONTRACT_ON_PROVIDER FOREIGN KEY (provider_id) REFERENCES t_provider (id);

ALTER TABLE t_cash_contract ADD CONSTRAINT FK_T_CASHCONTRACT_ON_STORE FOREIGN KEY (store_id) REFERENCES t_store (id);
