
CREATE TABLE t_card_transaction (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   giving_bank_account_id INT NOT NULL,
   receiving_bank_account_id INT NOT NULL,
   sum DOUBLE PRECISION NOT NULL,
   CONSTRAINT pk_t_cardtransaction PRIMARY KEY (id)
);

ALTER TABLE t_card_transaction ADD CONSTRAINT FK_T_CARDTRANSACTION_ON_GIVING_BANK_ACCOUNT FOREIGN KEY (giving_bank_account_id) REFERENCES t_account (id);

ALTER TABLE t_card_transaction ADD CONSTRAINT FK_T_CARDTRANSACTION_ON_RECEIVING_BANK_ACCOUNT FOREIGN KEY (receiving_bank_account_id) REFERENCES t_account (id);

CREATE TABLE t_card_contract (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   provider_id INT NOT NULL,
   store_id INT NOT NULL,
   product_id INT NOT NULL,
   amount INT NOT NULL,
   signed_date date NOT NULL,
   card_transaction_id INT NOT NULL,
   CONSTRAINT pk_t_cardcontract PRIMARY KEY (id)
);

ALTER TABLE t_card_contract ADD CONSTRAINT FK_T_CARDCONTRACT_ON_CARD_TRANSACTION FOREIGN KEY (card_transaction_id) REFERENCES t_card_transaction (id);

ALTER TABLE t_card_contract ADD CONSTRAINT FK_T_CARDCONTRACT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES t_product (id);

ALTER TABLE t_card_contract ADD CONSTRAINT FK_T_CARDCONTRACT_ON_PROVIDER FOREIGN KEY (provider_id) REFERENCES t_card_provider (id);

ALTER TABLE t_card_contract ADD CONSTRAINT FK_T_CARDCONTRACT_ON_STORE FOREIGN KEY (store_id) REFERENCES t_store (id);
