CREATE TABLE t_discount (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   item_id INTEGER,
   discount_percentage DOUBLE PRECISION,
   discount_applied_date date NOT NULL,
   type VARCHAR(255),
   CONSTRAINT pk_t_discount PRIMARY KEY (id)
);

ALTER TABLE t_discount ADD CONSTRAINT FK_T_DISCOUNT_ON_ITEM FOREIGN KEY (item_id) REFERENCES t_item (id);